language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: c2Kb5wAm6j561o3+X6aZVldAhj1+r5lczI4t6PcBmCglwUCE4Y1pk3zsust81aCDyzCMyQc+j+InGrX6S80SDsITc1P5yldKcwmB8ATAY58iTy4V+7L69oG+W1YYHLxaZ8g1K/1+7MHFNFf1PMWboVHABh/A2KRCtekOCGpFIhe8yjr1v9il3ZPP9sxyP3r+b20v1GflsLHy3VCSidCBuaTAAo6yPgjSNoGXB8gW1yGpVto23qOPrIGOa9AxeyBUDaiz0KIvYyMw7cvBWtIQuJjHXZAJNm3eMIcwcpjrRQnt3hjDPC/UxxptTcn5PBW7finpum62RH8BwNhHncD3vivsOXzbSEr2JrZlhPKxsZPLXZf8XnRV4i/PqfK09+bhAqjpPj/wg+dmDw0uQOPkPR1SQvM3mv2zmYVEHs8QPe+3rojU+o29em3xoxSRc6hinLs21liGt2s68Fu59ft9YZRHPZrmt08uXjrNnOnlkz4laYPLXwDQ/WYR/B/Orhce9yR0GRCI9qGz+88OqvGwNZf/wJKgasHZspMBWQhqvClFtWz2IFKXEIMTw7ayrW1npCVcmpLFVzMr4BxjXywxsp5v91Zlf/pOfSqyB832mUQfB3dUwM/ur5aV/7ynx0oEgjrBTqJ/b4dORMy5FwG+33MSz7hhTBCyUDX04MrNM2Q=
  - secure: Dz+bBzd7FC42Md3KNL6zycnBgSlBf2eYRLlMksR2m7lkgoP7hrsdUcNYzotGH3Qdd8K+y/fadsH61zqr/7TaZ65T/uOMBSlw8w5q9tIVefiLyh/x7idHd5BS3mPLEHY4NTeqzY3yiZy8P/yBp/1dnkp3jAonX2royCt9twRoTMNG/AgK5QWj3OMdgcsSe/7WBNs7ZkpAomXZR1FoUkTMmrbOi7n/s73HCmg5hqKLx6muyoycXKyZ2D/Lm/PW87jJ8e0i5GqsH+BXPoyy2rnRZR1VRUPEoFfzSbr87IniGQODviISLFkLEMZWDJxOos9DK61sL/Ib/Sx0IB8YPjkua2/+pQp5lXgDJtOPRiR8b2bUtua3IYUGx8TXVicYjBDisNJpo2k585aBS0XS1B0bDhiAVhs9/2TJ91y2SA+vv4nEra0NjnwIHkxyWi7VTbwrZptqyKKVKoBA0R9/eR3phBJw0Bn2FYxh4QQmqIqFvZMFjM9gU9XObDADo268qEBmUaakNa0/CE7l6VcAg8io6q1aRM7FQuzU4JBMZTbDDm0/AX6pVnSeahp54C/hl8+vrlZrR3/eBA791mKk0Cl1VFQqRmIxOEUTpdLQynl/ks7EIK3J31HpYeL+x+3AbCv92+EIMTqg9H0SUm2m0uOKOuC53F1r5Fvpw90/WBeOCU4=
