language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: zgZzm9dxhYrDMyEbcprJuEWkLds1OPWVWrh5m2UiNAGQJzmxL3v1CKv/qoVPgqyzdKjPEra2cunW0edGRMnBEHzolgLCGO3puNPGMBr6zm7TQrhRsP3RGc2V1QJXc42WpUS9Tzc3SZW/THw/TtOoIj6k7+iTu8urHGb+Sp0pTnVWzQkF63QfirgQnhplOk/bn3/KD1xvFbT3NPNn7mYnKe4xTv5tF08ZxSdh32IiUIE5BecRabjbv8kMjp3jG0a4fJrZbSQ57LHBZxFRFr+Uyq4ZVNKA4nwqYxrNxjAhGn1Piyda7I9iYJhaudWyIKFnuGiEVf2RlbQJWH4MNdTPMTCQ8s6ny08n3bpts6YN5KeBR+78HPXvO4BKYNvbqIQD74X34jtmtnbuB99i+HUM2S9hh03usJ951wpcMl9g8NdkRFTi2QQo2uHfh7NeB+4rme15jkZfV1xOMtRbDDC8v0tZnxsuQZ7x5VX1CpW7X+y24Veljc1ilA50QoMlNeCEgy7EVTLOGftiS8VThoM4bVxTS0VSbeRGK75S8g1ry+W3J4zwmkM5nb4/AYrQ6jKOO00RfBV585ixpvEtdUh4MKPiNKyI1aKCReQdOuvstdwfpQFL9f8fBb9clyqeZGxMxW9Bw5FH5pN2fS+DciFjYpy4amhXjDr6QedbOJ/UsEU=
  - secure: y3Ra4qiBR0u4v/TCySTcWgOUMt0t77djS4fY7s+5nChfukwHYuCtQGInF3dgY2gxlqIbZgGD224BEwp6bXGBfxHry/0ukK6P66IegM51RVYrJys3Z7GO6rZ3IcKkBia4lGxIa0hdzqA0m6itdM8oejxYW4iSYVHPU8L7lqyw65udjTwrfarIWy1e493iQQ4z0cVCxAbmtCPbPQNqQfjXluuxHNM6lc/p8TfQUDExAvUh8dQTZ6RnTDDBK6S9W9cjrDbk0VK3q2fX65FvXlZe+l76lebNM+r2m9Un3yCMECMD57IOSjKjuhcuMrfbJFhps64zYFG9JiwBP4ShT4OxBrk1gIARq3I/c72phW/LhIip/ay20mHQ3j5/C97CeaO7YiGBCAkP6NNTlpMF1c5h4Bnk3xO7vxOI7AjdMomNe9rON/aB43XMfl5zGrx54qI8VZiLN6hxRS8C8Kxnu653XI7KG6pbhZENgBG+7xBJa/uxLyavsOR3KadNAVejLWJ9H1he4RhhpLYwbR303+50rTBIqr8Hn8VTDQj6N6w0p/D5rkPQEu3yPy7A/e417mSyyQ/PFeSZkjFndDbDBbMCyj2XHlET87SgmohbzTgYx2a6Ca5zqJx1ejcdOD9OVkOTT3Cp1NbxCqgvdifqUcN5H2Uypn16mKaHv/wg2jUR7EY=
