baseURL = "http://www.brichards.net/"
languageCode = "en-us"
title = "Brian Richards and his stuff"
theme    = "hugo-theme-robust"

[params]
    author = "Brian Richards"
    locale = "en-US"
    description = "A collection of material related to my teaching, writing, and coding."
    motto = "Specialization is for insects"
    avatar = "bulb514.jpg"
    contentType = "post"
    paginate = 10 

  # Fonts settings.
  googlefonts = "https://fonts.googleapis.com/css?family=Lobster|Lato:400,700" # Optional, Include google fonts.
  fontfamily = "Lato,YuGothic,'Hiragino Kaku Gothic Pro',Meiryo,sans-serif" # Optional, Override body font family.
  logofontfamily = "Lobster, cursive" # Optional, Override logo font.


    #rootlink = "/"
    # rootlink specifies where Root in menu.html links to. If it's not set then baseurl will be used.