baseurl = "https://www.brichards.net/"
title = "Brian Richards, writer"
languageCode = "en-us"
theme = "mero"
author = "Brian Richards"
description = "a blog of reading and writing updates"
copyright = "&copy; always. All rights reserved."
paginate = 10

disableKinds = ["taxonomyTerm"]

[params]
  dateFormat = "2006-01-02" 
  author = "Brian Richards"
  description = "a blog of reading and writing updates"
  mainImage = "images/headshot3.jpg"

[params.introduction]
   text = "a blog of reading and writing updates"

[params.social]
  [[params.social.list]]
  class = "fab"
  icon = "fa-linkedin-in"
  url = "#"

  [[params.social.list]]
  class = "fab"
  icon = "fa-github"
  url = "#"

  [[params.social.list]]
  class = "fab"
  icon = "fa-twitter"
  url = "#"

  [[params.social.list]]
  class = "fab"
  icon = "fa-stack-overflow"
  url = "#"  

[params.footer]
  message = "&copy; 2020"
