baseURL = "http://www.brichards.net/"
languageCode = "en-us"
title = "Brian Richards and his stuff"
theme    = "dream-plus"

[params]
    author = "Brian Richards"
    locale = "en-US"
    description = "A collection of material related to my teaching, writing, and coding."
    motto = "Specialization is for insects"
    avatar = "bulb-514.jpg"
    contentType = "post" 




    #rootlink = "/"
    # rootlink specifies where Root in menu.html links to. If it's not set then baseurl will be used.