baseURL: https://www.brichards.net/
languageCode: en-us
defaultContentLanguage: en
title: Brian Richards, writer
theme: blackburn
enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: Brian Richards and his stuff.
  homeMetaContent: Brian Richards and his stuff.
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: true

menu:
  menu.main:
    - name: Home
      pre: <i class='fa fa-list fa-fw'></i>
      url: /
      weight: 1
    - name: Blog
      pre: <i class='fa fa-list fa-fw'></i>    
      url: /post/
      weight: 2
    - name: Tags
      pre: <i class='fa fa-list fa-fw'></i>    
      url: /tags/
      weight: 3
    - name: About
      pre: <i class='fa fa-list fa-fw'></i>    
      url: /about/
      weight: 4

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2