baseurl         = "https://www.brichards.net/"
theme           = "sp-minimal"
languageCode    = "en-us"
title           = "Brian Richards and his stuff"
disqusShortname = ""
paginate        = 5

[params]
  title       = "SP-Minimal"
  subtitle    = "Another Minimalist Theme for Hugo"
  copyright   = "Released under the MIT license."
  authorImage = "images/bulb514.jpg"

  #"single" or "multi"
  renderType = "multi"
  #"simple" or "original"
  themeStyle = "simple"

  googleAnalytics = ""

  name = "EM"
  description = "Here is a description of your site."
  pageNotFoundTitle = "404 - Page not found"

