baseurl = https://www.brichards.net/
title = "Brian Richards, writer"
languageCode = "en-us"
theme = "blackburn"
author = "Brian Richards"
copyright = "&copy; always. All rights reserved."
canonifyurls = true
paginate = 10

[indexes]
  tag = "tags"
  topic = "topics"

[menu]
[[menu.main]]
  name = "About"
  pre = "<i class='fa fa-user fa-fw'></i>"
  weight = 2
  identifier = "about"
  url = "/about/"

